#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MScResearchTool.Mobile.Android.Resource", IsApplication=true)]

namespace MScResearchTool.Mobile.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010005
			public const int max = 2130771973;
			
			// aapt resource value: 0x7f010000
			public const int ringColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int ringProgressColor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int ringWidth = 2130771970;
			
			// aapt resource value: 0x7f010007
			public const int style = 2130771975;
			
			// aapt resource value: 0x7f010003
			public const int textColor = 2130771971;
			
			// aapt resource value: 0x7f010006
			public const int textIsShow = 2130771974;
			
			// aapt resource value: 0x7f010004
			public const int textSize = 2130771972;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int droidSplash = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int SplashBitMap = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int FILL = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int HideButton = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int IntegrateButton = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int MainProgressBar = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int ManualButton = 2131099655;
			
			// aapt resource value: 0x7f060003
			public const int OtherButton = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int ReconnectButton = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int STROKE = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int StartStopButton = 2131099654;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_manual = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_menu = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050003
			public const int MasterRT_DialogButton = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int Theme_MasterRT = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Theme_Splash = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int alertDialog = 2131034114;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RingProgressBar = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975};
			
			// aapt resource value: 5
			public const int RingProgressBar_max = 5;
			
			// aapt resource value: 0
			public const int RingProgressBar_ringColor = 0;
			
			// aapt resource value: 1
			public const int RingProgressBar_ringProgressColor = 1;
			
			// aapt resource value: 2
			public const int RingProgressBar_ringWidth = 2;
			
			// aapt resource value: 7
			public const int RingProgressBar_style = 7;
			
			// aapt resource value: 3
			public const int RingProgressBar_textColor = 3;
			
			// aapt resource value: 6
			public const int RingProgressBar_textIsShow = 6;
			
			// aapt resource value: 4
			public const int RingProgressBar_textSize = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
